### ISSUE TITLE
Observable.create 사용에 대해

### ISSUE THREAD

**Issue by probepark** [jungilhan/awesome-blogs-android#10]
https://github.com/ReactiveX/RxJava/wiki/Creating-Observables

advanced use only!

이렇게 나와있는데 realm 사용하면 asObservable 쓰는게 어떨까요?

**Comment by jungilhan** [comment]
아마도 그런 문구가 붙어있는 것은 Observable.create() 함수를 이용해서 Observable을 생성할 때는 좀 더 주의가 필요하기 때문인 것으로 보입니다.

아시다시피 Observable을 생성할 때 onNext(), onError(), onCompleted()를 적절히 호출해야 하는데요. onError()와 onCompleted()는 동시에 호출할 수 없는 상호 배타적 관계이고, 이 두 함수 중 하나가 호출된 이 후에는 옵저버의 어떠한 함수도 호출하지 않아야 하는 조건들 때문이 아닐까 싶습니다.

제가 아래 코드에서 Observable.create()를 사용한 이유는 realm 인스턴스를 같은 스레드 내에서 close() 해주기 위함이었습니다.
 * https://github.com/jungilhan/awesome-blogs-android/blob/develop/api/src/main/java/org/petabytes/api/source/local/AwesomeBlogsLocalSource.java#L29

해당 클래스의 isRead() 함수에서는 asObservable()을 사용하고 있어서 일관성 면에서 좀 떨어지기는 하는데요. asObservable()로 변경했을 때, realm 인스턴스를 생성한 스레드에서 종료할 수 있는 방법을 좀 찾아보겠습니다. (isRead() 함수는 현재 UI 스레드에서만 호출되서 문제가 없는 상태인데 이 부분도 코드에서 잘 설명될 수 있도록 보완이 필요한 부분입니다.)

**Comment by probepark** [comment]
@jungilhan 
다른 이슈에 댓글 달았습니다.
