### ISSUE TITLE
Code 질문

### ISSUE THREAD

**Issue by probepark** [jungilhan/awesome-blogs-android#14]
```java
    @Override
    public Observable<Feed> getFeed(@NonNull final String category) {
        return localSource.getFeed(category)
            .flatMap(new Func1<Feed, Observable<Feed>>() {
                @Override
                public Observable<Feed> call(@Nullable Feed feed) {
                    return feed != null ? Observable.just(feed)
                        .doOnTerminate(new Action0() {
                            @Override
                            public void call() {
                                remoteSource.getFeed(category)
                                    .onErrorResumeNext(Observable.<Feed>empty())
                                    .subscribe();
                            }
                        }) : remoteSource.getFeed(category);
                }
            });
    }
```

여기서 의도하는게 local 에 있으면 로컬 먼저
로컬에 없으면 remote 로 가져 올려는 건가요?
doOnTerminate 안에 있는게 어떤걸 하는건지 정확히 모르겠어요~

항상 remote 에 질의하는거라면 local expire 타임을 정하고

Observable.concat 을 쓰는게 어떠까요?

**Comment by jungilhan** [comment]
맞습니다. 로컬 DB에 피드가 있으면 해당 정보를 보여주고, 없으면 서버로 리퀘스트를 하는 부분입니다. doTerminate는 로컬에 있는 정보를 보여주고, 서버로 최신 정보를 다시 요청하기 위한 코드입니다. 서버에서 응답을 받으면 아래 코드에 의해서 로컬 DB를 업데이트 합니다. 

https://github.com/jungilhan/awesome-blogs-android/blob/develop/api/src/main/java/org/petabytes/api/Api.java#L26

getFeed()를 호출하는 곳에서는 서버에서 내려준 Feed를 직접적으로 사용하지 않기 때문에(UI에서 서버 응답을 기다릴 필요가 없기 때문에) 이렇게 한 것인데요. 우선 concat()의 경우는 이벤트가 두 번 발행되기 때문에 맞지 의도와 맞지 않을 것 같습니다. switchMap은 사용해 본적은 없지만 문서를 보니 이것도 의도와 다른 것 같습니다. 

그리고 만료 시간 등을 이용해서 저 정교하게 처리해야 하는 부분은 맞습니다! 그나저나 @probepark 서버 개발자 아니었어요? 👍

**Comment by probepark** [comment]
@jungilhan 
요새 rxjava 랑 안드도 합니다..
쫌 짜보고 다시 말씀드릴게요 
Observable.concat( local, remote) .first() 하면 될거 같아요

local 에서 hit 되면 item emit 한번만하고
miss 되면 remote 로 가면 될거 같아요

매번 리모트로 호출해도 비용이니 expire time 만 잘 잡으면 될거 같아요.

**Comment by BenjaminKim** [comment]
@probepark 은 Rx가 있는 곳이라면 어디라도 달려간다고 함.

**Comment by jungilhan** [comment]
first를 하게 되면 첫번째 옵저버블의 아이템이 발행되고, concat이 완료되기 떄문에 두번째 옵저버블은 실행되지 않습니다.

**Comment by probepark** [comment]
첫번째에서 Observable.empty 가 되면 두번째꺼가 실행되지 않아요?

**Comment by probepark** [comment]
http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/
이걸 참고하고 있어요.

**Comment by jungilhan** [comment]
Observable.empty면 두번째가 실행되지만 그건 최초 로컬에 데이터가 없을 때, 케이스만 해당 될 것 같아요. 위 블로그에서는 가장 빠른 소스를 선택하는거지만 어썸블로그에서는 항상 로컬에 있는 데이터를 가져온다.는 부분에서 차이가 있어서 사례가 조금 다른 것 같아요.

**Comment by probepark** [comment]
@jungilhan 
네 어떤 말씀이신지 이해했어요.

말씀듣고 다시 한번 고쳤는데 함 봐주세용~~

**Comment by ZeroBrain** [comment]
그부분 코드의 의도는

```
if (로컬데이터 있음) {
  try { return 로컬 데이터; } finally { 서버데이터 갱신; }
} else {
  서버 to 로컬 데이터 저장;
  return 서버 데이터;
}
```

전 이부분에 대해서 오히려 null 처리에 대한 부분을 어떻게 해야하냐로 고민하고 있었어요.

로컬 데이터 == null 일 때 서버 데이터를 반영하도록 했는데

RxJava2 에서는 null 자체가 emit 될 수 없도록 되어 있기 때문에 Maybe 라는 API를 넣었어요.
저는 이걸 어떻게 반영해야 나중에 RxJava2 로 전환할 때 soft landing 할 수 있느냐로 고민하고 있었어요.

**Comment by probepark** [comment]
@ZeroBrain 넹. 일단은 Observable 에 null 안들어가게 했어요.

```java
    @Override
    public Observable<Feed> getFeed(@NonNull final String category) {
        Observable<Feed> local = localSource.getFeed(category);
        Observable<Feed> remote = local.isEmpty().flatMap(new Func1<Boolean, Observable<Feed>>() {
            @Override
            public Observable<Feed> call(Boolean empty) {
                Observable<Feed> remoteObservable = remoteSource.getFeed(category);
                return empty ? remoteObservable : remoteObservable.ignoreElements();
            }
        });
        return Observable.concat(local, remote);
    }

```
이렇게 고치긴 했는데.
더 좋은방법 없으까요?

**Comment by ZeroBrain** [comment]
```java
class Local {
    @Override
    public Observable<Feed> getFeed(@NonNull final String category) {
        return Observable.defer(() -> {
                Realm realm = Realm.getInstance(config);
                try {
                    Feed feed = realm.where(Feed.class).equalTo("category", category).findFirst();
                    return feed != null ? Observable.just(realm.copyFromRealm(feed)) : Observable.<Feed>empty();
                } finally {
                    realm.close();
                }
            }
        });
    }
}
```

```java
class Api {
    @Override
    public Observable<Feed> getFeed(@NonNull final String category) {
        return localSource.getFeed(category)
                .switchIfEmpty(Observable.defer(new Func0<Observable<Feed>>() {
                    @Override
                    public Observable<Feed> call() {
                        return remoteSource.getFeed(category);
                    }
                }));
    }
}
```

local 에서는 `defer()` (반환이 observable) 로 처리를 하고 null 여부에 따라 `Observable.empty()` 로 처리하게 한뒤에
api 에서는 `switchIfEmpty()` 오퍼레이터를 써서 remote 를 콜하도록 해봤어요.

https://github.com/ZeroBrain/awesome-blogs-android/blob/remove_nullable/api/src/main/java/org/petabytes/api/Api.java#L31

**Comment by probepark** [comment]
@ZeroBrain empty 이어도 remoteSource.getFeed(category); 가 실행되어야 하지 않어요?

**Comment by jungilhan** [comment]
@probepark 네 방금 코드를 봤는데 ignoreElements()를(이게 있는지 이제 알았음) 사용하면 잘 동작하겠네요.

**Comment by probepark** [comment]
@jungilhan 넹 저도 책에서만 본거 인제 써봤어요. ㅎㅎ
더 좋은 방법이 있는지 궁금합니다.

**Comment by ZeroBrain** [comment]
@probepark `switchIfEmpty()` 를 통해서 local 에서 emit 대상이 없으면 Remote.getFeed 로 전환하도록 했어요.

**Comment by jungilhan** [comment]
@probepark, @ZeroBrain 제가 생각하지 못한 방법이라 신선하네요. 사실 저도 이부분 고민 좀하다가 '아 몰라' 하고 작성 한 부분인데 귀신같이 이런걸 또 찾아내시다니...

**Comment by probepark** [comment]
@ZeroBrain 아 말을 잘못했네요
local 에 데이터가 있어도 remote 로 요청하는게 스펙인거 같아요
switchIfEmpty 쓰면 empty 가 아닐때도 remote 날라가요?

글고 하일라이팅은 어찌 하나요.

**Comment by ZeroBrain** [comment]
아...무조건 remote 를 콜해야하는군요.

**Comment by jungilhan** [comment]
```하이라이팅은```이렇게

**Comment by probepark** [comment]
내일 다시 고민해보겠습니다.

더 좋은 방법이 있는지..

**Comment by ZeroBrain** [comment]
markdown editor 에서 `<>` 선택하세요.

**Comment by jungilhan** [comment]
<pre>```하이라이팅```</pre> 저는 보통 이렇게 작성해요.

**Comment by probepark** [comment]
옙 다들 <감사합니다.>

```감사합니다.```

@jungilhan @ZeroBrain

**Comment by probepark** [comment]
잼있네요 같이하니까 ㅋㅋ

**Comment by jungilhan** [comment]
@ZeroBrain 말씀하신 것처럼 저도 Observable에서 null을 리턴하지 않도록 하고 싶은데, defer로 처리하는 부분이 좋아보이네요.

**Comment by jungilhan** [comment]
그리고 스펙은 제가 편의상 정한 것이니 언제든 변경 가능합니다. 저도 내일 좀 더 고민해볼게요. :)

**Comment by ZeroBrain** [comment]
```
// Api.class
@Override
public Observable<Feed> getFeed(@NonNull final String category) {
    return localSource.getFeed(category)
        .doOnNext(new Action1<Feed>() {
            @Override
            public void call(Feed data) {
                remoteSource.getFeed(category)
                    .onErrorResumeNext(Observable.<Feed>empty())
                    .subscribe();
            }
        })
        .switchIfEmpty(Observable.defer(new Func0<Observable<Feed>>() {
            @Override
            public Observable<Feed> call() {
                return remoteSource.getFeed(category);
            }
        }));
}
```

[최종적으로는 이렇게 해봤어요.](https://github.com/ZeroBrain/awesome-blogs-android/blob/remove_nullable/api/src/main/java/org/petabytes/api/Api.java#L38)

local == null -> Observable.empty() -> switchIfEmpty() -> remote.getFeed() -> subscribe()
local != null -> doOnNext() --(remote.getFeed)--> subscribe()

**Comment by ZeroBrain** [comment]
코드가 굉장히 불편하네요... 잠자고 좀 더 생각해볼게요

**Comment by ZeroBrain** [comment]
피하고 싶었지만 custom operator 를 고민해야봐야겠어요.

**Comment by probepark** [comment]
https://github.com/probepark/awesome-blogs-android/commit/4ca48359ce46f3850027060605c9257e47fcce20

저는 custom 없이 이게 최선이라고 생각합니다..
진짜 자야겠..

**Comment by tilltue** [comment]
저도 동일한 Observable  을 swift 에서 구현한 내용이 있는데 올려봅니다.
class RealmAPI<M:Object,E> {
    typealias ApiType = Observable<E>
    typealias RealmToModelType = ([M]) -> E
    typealias ModelToRealmType = (E) -> [M]?
    typealias DeleteType = ([M],[M]) -> [M]
    typealias WriteType = (E) -> Void
    
    var api : ApiType!
    var mapper : RealmToModelType!
    var realmMapper : ModelToRealmType!
    var deleteMapper : DeleteType?
    var writeBlock : WriteType?
    
    var disposeBag = DisposeBag()
    
    func load(_ needsEmptyNext: Bool=false) -> Observable<E> {
        return Observable.create{ [weak self] observer in
            guard let sself = self else { return Disposables.create{ } }
            if let realm = try? Realm() {
                let objects: [M] = realm.objects(M.self).map{ $0 as M }
                if objects.count > 0 {
                    observer.on(.next(sself.mapper(objects)))
                }else if needsEmptyNext {
                    observer.on(.next(sself.mapper([])))
                }
            }
            sself.api.subscribe(onNext:{ [weak self] element in
                guard let sself = self, let realm = try? Realm() else { observer.on(.completed); return }
                let objects : [M] = realm.objects(M.self).map{ $0 as M }
                if let realmObject: [M] = sself.realmMapper(element) {
                    if let writeBlock = sself.writeBlock {
                        writeBlock(element)
                    } else{
                        try? realm.write {
                            if let deleteMapper = sself.deleteMapper {
                                let deleteObjects: [M] = deleteMapper(objects,realmObject)
                                realm.delete(deleteObjects)
                            }
                            realm.add(realmObject, update: true)
                        }
                    }
                }
                observer.on(.next(element))
                observer.on(.completed)
            },onError:{ error in
                observer.on(.error(error))
            },onCompleted: { _ in
                observer.on(.completed)
            }).addDisposableTo(sself.disposeBag)
            return Disposables.create{
                sself.disposeBag = DisposeBag()
            }
        }
    }
}
realm Object 여러 모델들을 Generic Type 으로 받도록되어있고 ( 이를 위한 읽고 쓰고...등의 mapper가 필요 )
DB에서 있으면 먼저 이벤트를 보내주고 ( 없으면 빈 이벤트를 보낼지는 선택 )
서버 응답을 받으면 필요에 따라 DB 에 업데이트 하고, 해당 이벤트를 전달하고 종료하도록 했어요.
깔끔하게 다듬을 부분이 있다면 조언을 구합니다!

**Comment by jungilhan** [comment]
@ZeroBrain님이 마지막에 올려주신 코드가 좋아보입니다. (전혀 불편해보이지 않아요) switchIfEmpty()를 쓰는 부분으로 인해서 코드가 좀 더 보기 편하네요. switchIfEmpty 내의 Observable.defer()는 사실 상 효과가 없을 것 같은데, 이 부분은 빼도 되지 않을까요?

**Comment by ZeroBrain** [comment]
@jungilhan `defer()` 를 써야 `switchIfEmpty()` 가 필요한 상황에서 `remoteSource.getFeed()` 동작하지 않을까요?

`switchIfEmpty(remoteSource.getFeed())` 하면 empty 가 아닌 상황에서 무조건 호출이 될 것 같은데요.

PR 로 전환하도록 하겠습니다. :)

**Comment by jungilhan** [comment]
switchIfEmpty()가 localSource에서 아무런 아이템을 발행하지 않고 종료를 발행 했을 때, remoteSource의 아이템이 발행되는게 아닌가요? 그래서 localSource가 아이템을 발행하면 switchIfEmpty의 옵저버블은 호출되지 않을 것 같습니다.

**Comment by ZeroBrain** [comment]
defer 는 예약했다가 subscribe 가 붙으면 실제로 내부의 create 동작이 되요.

```java
switchIfEmpty(remote.getFeed());
```
이처럼 코드가 되면 remote.getFeed 는 동작하게 되어
api call -> save -> view-feed 로 전환 하는 것까지는 동작하기 되어서
empty 일 때만 api call 을 가져오도록 하려는 의도에요.

**Comment by jungilhan** [comment]
해당 코드에서의 subscribe는 localSource 소스를 구독하는 것이기 때문에 (empty()를 발행하기 전까지는) remote.getFeed의 subscribe(구독이)가 발생하지 않는다고 이해하고 있습니다. 그렇기 때문에 이 부분에서 defer()가 하는 지연 생성은 의미가 없을 것이라는 의견이고요. 

해당 케이스를 간단하게 테스트 코드로 만들어보면 다음과 같이 될 텐데요. 이 때 "World" 옵저버블의 doOnSubscribe 콜백은 호출되지 않습니다. 
```
Observable.just("Hello")
            .switchIfEmpty(Observable.just(", World!")
                .doOnSubscribe(() -> Timber.d("OnSubscribe")))
            .subscribe(Timber::d);
```

**Comment by ZeroBrain** [comment]
아하 그렇군요. defer 코드를 삭제하고 다시 반영하도록 하겠습니다.

**Comment by jungilhan** [comment]
@ZeroBrain 풀리퀘스트 머지 후 테스트를 해보니 local 옵저버블의 onSubscribe가 호출되기도 전에 switchIfEmpty의 폴백 옵저버블(remote)이 먼저 실행되버리는군요. 왜 api call이 첫번째로 수행된다고 말씀하셨는지 알겠습니다. 이렇게 동작하는 원인은 찾지 못했는데 이 부분은 확인되면 다시 공유 하겠습니다.

**Comment by jungilhan** [comment]
@ZeroBrain 이런, 제가 엉뚱한 곳에서 문제를 찾고 있었네요. switchIfEmptry의 폴백 옵저버블이 먼저 실행되는 것이 아니라 locaSrouce의 doOnNext() 콜백에 의해 서버 Api가 호출되는 것이었습니다. Retrofit의 Http 요청이 같은 스레드 내에서 호출되다보니 doOnNext() 함수가 완료되기 전까지 localSource의 onNext()가 호출되지 않아 발생하는 현상입니다. (https://github.com/jungilhan/awesome-blogs-android/commit/1d75a3e7fd6e925ab5d9df1ec13a2a27303d67d4)

제가 헛다리를 몇 번 짚어서 최종 정리를 하면, 
 - switchIfEmpty에 념겨줄 폴백 옵저버블을 생성할 때, defer()를 사용해 실제 폴백 옵저버블이 사용(구독)되는 시점에 생성하는 것이 좋다.
 - switchIfEmpty는 소스 옵저버블이 empty인 상황에서만 폴백 옵저버블의 구독이 일어난다. (https://github.com/ReactiveX/RxJava/blob/v1.2.6/src/main/java/rx/internal/operators/OperatorSwitchIfEmpty.java#L68)

**Comment by probepark** [comment]
subscribe 가 일어날때만 실행되기때문에 
defer가 필요없지 않나요?

**Comment by probepark** [comment]
마무리 된거 같으니
이 스레드는 접고 필요하면 다시 만들도록 할게요
