### ISSUE TITLE
특정 글을 불러올떄 내용이 짤리는 현상

### ISSUE THREAD

**Issue by KimKyung-man** [jungilhan/awesome-blogs-android#15]
앱을 사용할 때
네이버 포스팅이 제대로 보이지 않는 버그가 있습니다. _(ex 티몬)_

제 기기에서만 발생하는 문젠가 싶기도하구요 -_-
제 기기는 KT 갤럭시 S5 광대역 LTE 입니다.

**Comment by BenjaminKim** [comment]
보통 RSS 로 글 발행을 할 때 글 발행자는 글 전체를 발행할 지, 내용의 일부만 발행할지를(본인들의 사이트로 트래픽을 유입시키기 위해서) 결정합니다.
티몬은 글 일부만 발행하기로 선택 한 것 같습니다.

버그처럼 보이지 않도록 UI 를 조금 고민해볼 필요가 있겠네요.

**Comment by jungilhan** [comment]
@KimKyung-man 제보 감사하니다. 일부 발행된 글의 전체 내용을 가져올 수는 없을 것 같고, UI를 조금 손보는 방향으로 개선하겠습니다. 다음 배포에 반영시켜볼게요! :)

**Comment by BenjaminKim** [comment]
참고로 현재는 글 제목을 누르면 해당 사이트로 이동하게되어있어요.

**Comment by jungilhan** [comment]
@KimKyung-man 다음과 같이 '페이지 방문하기' 버튼이 추가됐습니다. (근본적인 수정은 아니지만) 다음 배포 버전에서 사용해보시고 또 피드백 부탁드려요~

![screenshot](https://dl.dropboxusercontent.com/u/539401/awesomeblogs/Screenshot_1487845466.png)
