### ISSUE TITLE
'ㅎ' 폰트가 제대로 그려지지 않는 현상

### ISSUE THREAD

**Issue by jungilhan** [jungilhan/awesome-blogs-android#16]
작성자 이름의 'ㅎ'이 흐리게 나오는 현상, 스크린샷 참고하기
![Screenhot](https://dl.dropboxusercontent.com/u/539401/awesomeblogs/Screenshot_1487821613.png)

**Comment by ZeroBrain** [comment]
동일현상 발생.

![2017-02-23 07 54 09](https://cloud.githubusercontent.com/assets/4973428/23249657/d703e36c-f9e8-11e6-949e-30081d9cafa6.png)

**Comment by ZeroBrain** [comment]
동일현상 발생
Device : OnePlus 3
OS : Android N 7.0

![2017-02-23 07 54 09](https://cloud.githubusercontent.com/assets/4973428/23249709/0dbc7612-f9e9-11e6-9345-b27de974e991.png)
