### ISSUE TITLE
Api module retrolambda 적용

### ISSUE THREAD

**Issue by probepark** [jungilhan/awesome-blogs-android#21]
api 쪽에만 retrolambda 가 없는거 같아요

buildscript 는 공통으로 사용하면 좋을거 같은데 어떤가요?

**Comment by jungilhan** [comment]
현재 retrolambda는 app 모듈에서만 사용하고 있습니다. 가급적이면 라이브러리의 디펜던시 스코프를 줄이는 것을 지향하기 때문에 의도적으로 그렇게 한 것인데요. 이 부분은 좀 더 지켜보고 결정하면 좋겠습니다. 지금까지는 혼자 작업을 했기 때문에 api 모듈에 람다가 없어도 특별한 불편함을 느끼지 못했는데요. 코드를 커밋하는 분들이 계속 생기면 기존의 기준과 람다의 이점 두가지를 놓고 판단해볼 수 있을 것 같습니다. 😄

**Comment by probepark** [comment]
네 그럼 코드베이스 커지면 다시 열게요
