### ISSUE TITLE
서버 API 요청 좀 더 정교하게 처리하기

### ISSUE THREAD

**Issue by jungilhan** [jungilhan/awesome-blogs-android#22]
같은 카테고리의 경우는 중복 요청을 하지 않도록, 특정 시간 내의 요청은 무시하도록 처리할 필요가 있음

**Comment by probepark** [comment]
@jungilhan 
특정 시간은 몇으로 하면 좋을까요?
5분?

**Comment by jungilhan** [comment]
시간의 경우는 데이터베이스에 Feed를 저장할 떄 expires 필드를 추가할 생각인데요. 이렇게 하면 쿼리 시, 조건을 하나 추가하는 정도로 처리할 수 있을 것 같습니다.

**Comment by probepark** [comment]
플립보드처럼 로컬에 있는데이터 보여주다가 새로 받아온 데이터에 새거가 있으면 상단에 새글 이라는걸 보여주면 어떨까요

**Comment by jungilhan** [comment]
아 요거 제가 답변을 안했네요. 시간은 일단 5분으로 설정해뒀습니다. 새글 표시도 한번 고민해볼게용! 👍
