### ISSUE TITLE
CI 연동

### ISSUE THREAD

**Issue by probepark** [jungilhan/awesome-blogs-android#23]
- 테스트 깨짐 방지
- 테스트 코드 커버리지 확인

**Comment by ZeroBrain** [comment]
테스트 프레임웍도 JUnit & Robolectric 으로 통일하는게 어떨까요?

**Comment by probepark** [comment]
@ZeroBrain 통일하는거 좋습니다.
안드로이드 test instrument 는 옛날 방식이어서 그런거죠?

**Comment by jungilhan** [comment]
Robolectric는 귀동냥으로만 알고만있었는데 저도 이번 기회에 경험해 볼 수 있는 좋은 기회가 될 것 같습니다.

**Comment by ZeroBrain** [comment]
최신은 Android Test Support Library 쪽이 좀더 최신이긴 한대
이건 기기/에뮬 이 있다는 가정하에 되는 것이라
Travis CI 환경에는 Robolectric 이 더 맞을거라 생각해서요.

**Comment by jungilhan** [comment]
그 전에 테스트 코드에 대한 썰도 풀어보면 재미있을 것 같아요. 어썸블로그는 테스트 코드를 거의 만들지 않았지만 제가 참여했던 이전 몇몇 프로젝트에서는 MVP 패턴을 적용해보면서 모델과 프레젠터에 대한 테스트를 주로 만드는 방식을 사용했었습니다. 뷰(UI)의 경우는 요구사항의 변경과 업데이트 속도가 상대적으로 빠르편이다 보니 테스트가 금새 구닥다리가 되어버려 이게 오히려 부담으로 작용할 때가 있더라고요. 그래서 뷰에 대한 테스트는 경험이 없는 편입니다.

제가 팀에서 항상 테스트를 만들자.라고 주장하던 편이었는데 정작 어썸블로그에는 테스트를 만들지 않아서 마침 등이 가렵기도 했는데 이번에 새로운 테스트 프레임워크를 도입해보는 것도 좋을 것 같고, 다양한 의견 나눌 수 있었으면 좋겠습니다.

그리고 어썸블로그의 Coordinator가 현재는 로직과 뷰를 모두 갖고 있다보니 아무래도 테스트를 만들기 좋은 구조는 아닙니다. 제가 이 부분을 좀 더 테스트가 쉬운 구조로 변경해 볼 수도 있을 것 같습니다.

**Comment by probepark** [comment]
이것도 label 하나 달아주세요 ㅋㅋ

**Comment by ZeroBrain** [comment]
Coordinator 쪽을 어제 봤는데 아직 어떻게 변경될지 궁금해지네요. :)
